from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOG_DIR = PROJECT_ROOT / "logs"
DEBUG_FRAME_DIR = PROJECT_ROOT / "debug_frames"

USB_CAMERA_INDEXES = range(0, 6)
USB_FRAME_WIDTH = 640
USB_FRAME_HEIGHT = 480
USB_TARGET_FPS = 15
USB_MAX_RUNTIME_FAILURES = 10

PHONE_FRAME_WIDTH = 640
PHONE_FRAME_HEIGHT = 480
PHONE_TARGET_FPS = 10
PHONE_JPEG_QUALITY = 65

SERVER_HOST = os.getenv("STRETCH_SERVER_HOST", "0.0.0.0")
SERVER_PORT = int(os.getenv("STRETCH_SERVER_PORT", "8000"))
USE_HTTPS = os.getenv("STRETCH_USE_HTTPS", "0").lower() in {"1", "true", "yes"}
SSL_CERTFILE = os.getenv("STRETCH_SSL_CERT", "")
SSL_KEYFILE = os.getenv("STRETCH_SSL_KEY", "")

DASHBOARD_WINDOW_NAME = "Smart Stretch Coach Station"
DASHBOARD_WIDTH = 1280
DASHBOARD_HEIGHT = 720
DASHBOARD_LIVE_AREA_WIDTH = 880
DASHBOARD_LIVE_AREA_HEIGHT = 660

SOURCE_USB = "USB_CAMERA"
SOURCE_PHONE = "PHONE_QR"
SOURCE_NONE = "NO_CAMERA"
